### PR TITLE
Refactor api doc

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-1d044dadd3/docs/cloud-queues/v1/developer-guide/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-13601b2161/docs/cloud-queues/v1/developer-guide/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-be6b454604/docs/cloud-queues/v1/developer-guide/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-17c2b73a00/docs/cloud-queues/v1/developer-guide/).

**Comment by cyrichardson** [comment]
LGTM merging

**Pull request merged**
